# Generated by Django 5.2.17 on 2026-08-30 09:26

import shorty_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2048)),
                ('short_code', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True, default=shorty_app.models.default_expiration)),
            ],
        ),
    ]
